*******************************************************************************
****** NAND3 schematic lab2024  <vs>  NAND3 layout lab2024
*******************************************************************************

Filter/Reduce statistics only. Network matching was OK.
                                                                                                                                                                   
Pre-expand Statistics                      
======================                          Original       
Cell/Device                               schematic  layout
(PMOS4) MOS                                       3       3
(NMOS4) MOS                                       3       3
                                             ------  ------
Total                                             6       6

Reduce Statistics
=================                               Original             Reduced
Cell/Device                               schematic  layout   schematic  layout
(NMOS4) MOS                                       3       3           3       3
(PMOS4) MOS                                       3       3           3       3
                                             ------  ------      ------  ------
Total                                             6       6           6       6

Schematic and Layout Match
