0 0 dataAuditErrors
294 0 DEVICE Error: Illegal nmosh device
742 0 Process Modules : PHDNWA850 not available for this process module
746 0 Process Modules : PHDNWB850 not available for this process module
748 0 Version od SBD5 obsolte or missing
756 0 Process Modules : SBD5 not available for this process module
1230 0 ERC Warning : Name of Spiral not identified
1231 0 ERC Warning : INDDEF does not define a correct spiral or is not valid for this process
1248 0 ERC Warning : illegal layer under spiral
1261 0 ERC Warning : Each INDDEF shape must be marked with a single INDDEF text label
1263 0 ERC Warning : multiple text on INDEF
1276 0 Error: MET1 resistors (shorts) must be rectangular
1278 0 Error: Number of MET1 resistor terminals != 2
1290 0 Error: MET2 resistors (shorts) must be rectangular
1292 0 Error: Number of MET2 resistor terminals != 2
1304 0 Error: MET3 resistors (shorts) must be rectangular
1306 0 Error: Number of MET3 resistor terminals != 2
1318 0 Error: MET4 resistors (shorts) must be rectangular
1320 0 Error: Number of MET4 resistor terminals != 2
1330 0 RVIA1 Definition layer: does not open all via conncetion, is shorted
1333 0 RVIA1 Definition layer: truncates via1, device shorted
1334 0 RVIA1 Definition layer: does not define a device
1338 0 RVIA1 Definition layer: over METRES
1345 0 RVIA2 Definition layer: does not open all via conncetion, is shorted
1348 0 RVIA2 Definition layer: truncates via2, device shorted
1349 0 RVIA2 Definition layer : does not define a device
1353 0 RVIA2 Definition layer: over METRES
1361 0 RVIA3 Definition layer: does not open all via conncetion, is shorted
1364 0 RVIA3 Definition layer: truncates via3, device shorted
1365 0 RVIA3 Definition layer : does not define a device
1369 0 RVIA3 Definition layer: over METRES
1469 0 ERROR : POLY1 pin outside poly1
1470 0 ERROR : MET1 pin outside met1
1471 0 ERROR : MET2 pin outside met2
1473 0 ERROR : MET3 pin outside met3
1475 0 ERROR : MET4 pin outside met4
1476 0 ERROR : PAD pin outside pad metal
3819 0 malformed device NMOSH_device
3820 0 malformed device NMOSMH_device
3821 0 malformed device NMOS30M_device
3822 0 malformed device NMOS18T_device
3823 0 malformed device ESDPD12_device
3824 0 malformed device ESDPD18_device
3825 0 malformed device ESDPD26_device
3826 0 malformed device ESDPD30_device
3827 0 malformed device ESDFDN5_device
3828 0 malformed device ESDGCN5_device
3829 0 malformed device ESDFDP5_device
3830 0 malformed device ESDGCP5_device
3831 0 malformed device RNWELL_device
3832 0 malformed device RDIFFP_device
3833 0 malformed device RPOLY2_PSUB_device
3834 0 malformed device RPOLY2_NTUB_device
3835 0 malformed device RPOLY2PH_PSUB_device
3836 0 malformed device RPOLY2PH_NTUB_device
3837 0 malformed device RPOLYH_PSUB_device
3838 0 malformed device RPOLYH_NTUB_device
3839 0 malformed device RPOLY1_PSUB_device
3840 0 malformed device RPOLY1_NTUB_device
3841 0 malformed device PFUSE_device
3842 0 malformed device LAT2_device
3843 0 malformed device VERT10_device
3844 0 malformed device CPOLY_PSUB_device
3845 0 malformed device CPOLY_NTUB_device
3846 0 malformed device CVAR_device
3847 0 malformed device PROBE_device
3848 0 malformed device NMOSRF_device
3849 0 malformed device PMOSRF_device
3850 0 malformed device CPOLYRF_device
3851 0 malformed device RPOLY2RF_device
3852 0 malformed device RPOLYHRF_device
3853 0 malformed device SP014S300D_device
3854 0 malformed device SP020S180D_device
3855 0 malformed device SP026S200D_device
3856 0 malformed device SP037S180D_device
3857 0 malformed device SP047S180D_device
3858 0 malformed device SP050S155D_device
3859 0 malformed device SP090S155D_device
4382 0 unstable device for SP090S155D_device_Device_98
4383 0 unpreserved device SP090S155D_device_Device_98
4384 0 unstable device for SP050S155D_device_Device_97
4385 0 unpreserved device SP050S155D_device_Device_97
4386 0 unstable device for SP047S180D_device_Device_96
4387 0 unpreserved device SP047S180D_device_Device_96
4388 0 unstable device for SP037S180D_device_Device_95
4389 0 unpreserved device SP037S180D_device_Device_95
4390 0 unstable device for SP026S200D_device_Device_94
4391 0 unpreserved device SP026S200D_device_Device_94
4392 0 unstable device for SP020S180D_device_Device_93
4393 0 unpreserved device SP020S180D_device_Device_93
4394 0 unstable device for SP014S300D_device_Device_92
4395 0 unpreserved device SP014S300D_device_Device_92
4396 0 unstable device for RPOLYHRF_device_RES_91
4397 0 unpreserved device RPOLYHRF_device_RES_91
4398 0 unstable device for RPOLY2RF_device_RES_90
4399 0 unpreserved device RPOLY2RF_device_RES_90
4400 0 unstable device for CPOLYRF_device_CAP_89
4401 0 unpreserved device CPOLYRF_device_CAP_89
4402 0 unstable device for PMOSRF_device_Device_88
4403 0 unpreserved device PMOSRF_device_Device_88
4404 0 unstable device for NMOSRF_device_Device_87
4405 0 unpreserved device NMOSRF_device_Device_87
4406 0 unstable device for PROBE_device_Device_86
4407 0 unpreserved device PROBE_device_Device_86
4408 0 unstable device for CPMIM_device_Device_85
4409 0 unpreserved device CPMIM_device_Device_85
4410 0 unstable device for CMIM_device_no_cpmim_Device_84
4411 0 unpreserved device CMIM_device_no_cpmim_Device_84
4412 0 unstable device for CVAR_device_Device_83
4413 0 unpreserved device CVAR_device_Device_83
4414 0 unstable device for CPOLY_NTUB_device_CAP_82
4415 0 unpreserved device CPOLY_NTUB_device_CAP_82
4416 0 unstable device for CPOLY_PSUB_device_CAP_81
4417 0 unpreserved device CPOLY_PSUB_device_CAP_81
4418 0 unstable device for VERT10_device_BJT_80
4419 0 unpreserved device VERT10_device_BJT_80
4420 0 unstable device for LAT2_device_Device_79
4421 0 unpreserved device LAT2_device_Device_79
4422 0 unstable device for RVIA3_device_RES_78
4423 0 unpreserved device RVIA3_device_RES_78
4424 0 unstable device for RVIA2_device_RES_77
4425 0 unpreserved device RVIA2_device_RES_77
4426 0 unstable device for RVIA1_device_RES_76
4427 0 unpreserved device RVIA1_device_RES_76
4428 0 unstable device for RMET4_device_RES_75
4429 0 unpreserved device RMET4_device_RES_75
4430 0 unstable device for RMET3_device_RES_74
4431 0 unpreserved device RMET3_device_RES_74
4432 0 unstable device for RMET2_device_RES_73
4433 0 unpreserved device RMET2_device_RES_73
4434 0 unstable device for RMET1_device_RES_72
4435 0 unpreserved device RMET1_device_RES_72
4436 0 unstable device for PFUSE_device_RES_71
4437 0 unpreserved device PFUSE_device_RES_71
4438 0 unstable device for RPOLY1_NTUB_device_RES_70
4439 0 unpreserved device RPOLY1_NTUB_device_RES_70
4440 0 unstable device for RPOLY1_PSUB_device_RES_69
4441 0 unpreserved device RPOLY1_PSUB_device_RES_69
4442 0 unstable device for RPOLYZ_NTUB_device_Device_68
4443 0 unpreserved device RPOLYZ_NTUB_device_Device_68
4444 0 unstable device for RPOLYZ_PSUB_device_Device_67
4445 0 unpreserved device RPOLYZ_PSUB_device_Device_67
4446 0 unstable device for RPOLYH_NTUB_device_RES_66
4447 0 unpreserved device RPOLYH_NTUB_device_RES_66
4448 0 unstable device for RPOLYH_PSUB_device_RES_65
4449 0 unpreserved device RPOLYH_PSUB_device_RES_65
4450 0 unstable device for RPOLY2PH_NTUB_device_RES_64
4451 0 unpreserved device RPOLY2PH_NTUB_device_RES_64
4452 0 unstable device for RPOLY2PH_PSUB_device_RES_63
4453 0 unpreserved device RPOLY2PH_PSUB_device_RES_63
4454 0 unstable device for RPOLY2P_NTUB_device_Device_62
4455 0 unpreserved device RPOLY2P_NTUB_device_Device_62
4456 0 unstable device for RPOLY2P_PSUB_device_Device_61
4457 0 unpreserved device RPOLY2P_PSUB_device_Device_61
4458 0 unstable device for RPOLY2_NTUB_device_RES_60
4459 0 unpreserved device RPOLY2_NTUB_device_RES_60
4460 0 unstable device for RPOLY2_PSUB_device_RES_59
4461 0 unpreserved device RPOLY2_PSUB_device_RES_59
4462 0 unstable device for RDIFFN_device_RES_58
4463 0 unpreserved device RDIFFN_device_RES_58
4464 0 unstable device for RDIFFP_device_RES_57
4465 0 unpreserved device RDIFFP_device_RES_57
4466 0 unstable device for RNWELL_device_RES_56
4467 0 unpreserved device RNWELL_device_RES_56
4468 0 unstable device for ESDGCP5_device_Device_55
4469 0 unpreserved device ESDGCP5_device_Device_55
4470 0 unstable device for ESDFDP5_device_Device_54
4471 0 unpreserved device ESDFDP5_device_Device_54
4472 0 unstable device for ESDGCN5_device_Device_53
4473 0 unpreserved device ESDGCN5_device_Device_53
4474 0 unstable device for ESDFDN5_device_Device_52
4475 0 unpreserved device ESDFDN5_device_Device_52
4476 0 unstable device for ESDPD30_device_Device_51
4477 0 unpreserved device ESDPD30_device_Device_51
4478 0 unstable device for ESDPD26_device_Device_50
4479 0 unpreserved device ESDPD26_device_Device_50
4480 0 unstable device for ESDPD18_device_Device_49
4481 0 unpreserved device ESDPD18_device_Device_49
4482 0 unstable device for ESDPD12_device_Device_48
4483 0 unpreserved device ESDPD12_device_Device_48
4484 0 unstable device for SBD5_device_sbdcon_Device_47
4485 0 unpreserved device SBD5_device_sbdcon_Device_47
4486 0 unstable device for PHDNWB850_device_pad_barc_Device_46
4487 0 unpreserved device PHDNWB850_device_pad_barc_Device_46
4488 0 unstable device for PHDNWA850_device_ntub_Device_45
4489 0 unpreserved device PHDNWA850_device_ntub_Device_45
4490 0 unstable device for ZD2SM24_device_DIODE_44
4491 0 unpreserved device ZD2SM24_device_DIODE_44
4492 0 unstable device for P_NWD_device_DIODE_43
4493 0 unpreserved device P_NWD_device_DIODE_43
4494 0 unstable device for NWD_device_DIODE_42
4495 0 unpreserved device NWD_device_DIODE_42
4496 0 unstable device for P_PD_device_DIODE_41
4497 0 unpreserved device P_PD_device_DIODE_41
4498 0 unstable device for PD_device_DIODE_40
4499 0 unpreserved device PD_device_DIODE_40
4500 0 unstable device for P_ND_device_DIODE_39
4501 0 unpreserved device P_ND_device_DIODE_39
4502 0 unstable device for ND_device_DIODE_38
4503 0 unpreserved device ND_device_DIODE_38
4504 0 unstable device for PMOS30M_device_Device_37
4505 0 unpreserved device PMOS30M_device_Device_37
4506 0 unstable device for PMOSD30M_device_Device_36
4507 0 unpreserved device PMOSD30M_device_Device_36
4508 0 unstable device for NMOS18T_device_Device_35
4509 0 unpreserved device NMOS18T_device_Device_35
4510 0 unstable device for NMOS30M_device_Device_34
4511 0 unpreserved device NMOS30M_device_Device_34
4512 0 unstable device for NMOSMHL_device_Device_33
4513 0 unpreserved device NMOSMHL_device_Device_33
4514 0 unstable device for NMOSHL_device_Device_32
4515 0 unpreserved device NMOSHL_device_Device_32
4516 0 unstable device for NMOSMH_device_Device_31
4517 0 unpreserved device NMOSMH_device_Device_31
4518 0 unstable device for NMOSH_device_Device_30
4519 0 unpreserved device NMOSH_device_Device_30
4520 0 unstable device for PMOSMW_2N_device_Device_29
4521 0 unpreserved device PMOSMW_2N_device_Device_29
4522 0 unstable device for PMOSMW_3N_device_Device_28
4523 0 unpreserved device PMOSMW_3N_device_Device_28
4524 0 unstable device for PMOSMW_4N_device_Device_27
4525 0 unpreserved device PMOSMW_4N_device_Device_27
4526 0 unstable device for PMOSW_2N_device_Device_26
4527 0 unpreserved device PMOSW_2N_device_Device_26
4528 0 unstable device for PMOSW_3N_device_Device_25
4529 0 unpreserved device PMOSW_3N_device_Device_25
4530 0 unstable device for PMOSW_4N_device_Device_24
4531 0 unpreserved device PMOSW_4N_device_Device_24
4532 0 unstable device for NMOSMW_2N_device_Device_23
4533 0 unpreserved device NMOSMW_2N_device_Device_23
4534 0 unstable device for NMOSMW_3N_device_Device_22
4535 0 unpreserved device NMOSMW_3N_device_Device_22
4536 0 unstable device for NMOSMW_4N_device_Device_21
4537 0 unpreserved device NMOSMW_4N_device_Device_21
4538 0 unstable device for NMOSW_2N_device_Device_20
4539 0 unpreserved device NMOSW_2N_device_Device_20
4540 0 unstable device for NMOSW_3N_device_Device_19
4541 0 unpreserved device NMOSW_3N_device_Device_19
4542 0 unstable device for NMOSW_4N_device_Device_18
4543 0 unpreserved device NMOSW_4N_device_Device_18
4544 0 unstable device for PMOSML_WAFFLE_device_Device_17
4545 0 unpreserved device PMOSML_WAFFLE_device_Device_17
4546 0 unstable device for DPMOSM_device_Device_16
4547 0 unpreserved device DPMOSM_device_Device_16
4548 0 unstable device for PMOSML_device_Device_15
4549 0 unpreserved device PMOSML_device_Device_15
4550 0 unstable device for PMOSL_WAFFLE_device_Device_14
4551 0 unpreserved device PMOSL_WAFFLE_device_Device_14
4552 0 unstable device for PMOSL_device_Device_13
4553 0 unpreserved device PMOSL_device_Device_13
4554 0 unstable device for NMOSML_WAFFLE_device_Device_12
4555 0 unpreserved device NMOSML_WAFFLE_device_Device_12
4556 0 unstable device for NMOSML_device_Device_11
4557 0 unpreserved device NMOSML_device_Device_11
4558 0 unstable device for NMOSL_WAFFLE_device_Device_10
4559 0 unpreserved device NMOSL_WAFFLE_device_Device_10
4560 0 unstable device for NMOSL_device_Device_9
4561 0 unpreserved device NMOSL_device_Device_9
4562 0 unstable device for PMOSM_WAFFLE_device_Device_8
4563 0 unpreserved device PMOSM_WAFFLE_device_Device_8
4564 0 unstable device for PMOSM_device_MOS_7
4565 0 unpreserved device PMOSM_device_MOS_7
4566 0 unstable device for PMOS_WAFFLE_device_Device_6
4567 0 unpreserved device PMOS_WAFFLE_device_Device_6
4568 0 unstable device for PMOS_device_MOS_5
4569 0 unpreserved device PMOS_device_MOS_5
4570 0 unstable device for NMOSM_WAFFLE_device_Device_4
4571 0 unpreserved device NMOSM_WAFFLE_device_Device_4
4572 0 unstable device for NMOSM_device_MOS_3
4573 0 unpreserved device NMOSM_device_MOS_3
4574 0 unstable device for NMOS_WAFFLE_device_Device_2
4575 0 unpreserved device NMOS_WAFFLE_device_Device_2
4576 0 unstable device for NMOS_device_MOS_1
4577 0 unpreserved device NMOS_device_MOS_1
