0 0 dataAuditErrors
105 0 ILL_LAYER_PPLUS_DPL
152 0 ILL_LAYER_METCAP
183 0 ILL_ELEMENT_RPOLY2P
202 0 ILL_ELEMENT_RPOLYZ
306 0 DEVICE Error: Illegal nmosh device
339 0 ILL_LAYER_LVTDEF
356 0 NMOSW/NMOSMW for waffle trans we expect 1, 2, or 4 s/d conts, diffcont missing
358 0 NMOSW/NMOSMW for waffle trans we expect 1, 2, or 4 s/d conts, too much s/d cont
383 0 PMOSW/PMOSMW for waffle trans we expect 1, 2, or 4 s/d conts, diffcont missing
385 0 PMOSW/PMOSMW for waffle trans we expect 1, 2, or 4 s/d conts, too much s/d cont
776 0 Process Modules : PHDNWA850 not available for this process module
780 0 Process Modules : PHDNWB850 not available for this process module
782 0 Version od SBD5 obsolte or missing
790 0 Process Modules : SBD5 not available for this process module
952 0 ILL_LAYER_PFIMP
1306 0 ERC Warning : Name of Spiral not identified
1307 0 ERC Warning : INDDEF does not define a correct spiral or is not valid for this process
1324 0 ERC Warning : illegal layer under spiral
1337 0 ERC Warning : Each INDDEF shape must be marked with a single INDDEF text label
1339 0 ERC Warning : multiple text on INDEF
1354 0 Error: MET1 resistors (shorts) must be rectangular
1356 0 Error: Number of MET1 resistor terminals != 2
1370 0 Error: MET2 resistors (shorts) must be rectangular
1372 0 Error: Number of MET2 resistor terminals != 2
1386 0 Error: MET3 resistors (shorts) must be rectangular
1388 0 Error: Number of MET3 resistor terminals != 2
1402 0 Error: MET4 resistors (shorts) must be rectangular
1404 0 Error: Number of MET4 resistor terminals != 2
1414 0 RVIA1 Definition layer: does not open all via conncetion, is shorted
1417 0 RVIA1 Definition layer: truncates via1, device shorted
1418 0 RVIA1 Definition layer: does not define a device
1422 0 RVIA1 Definition layer: over METRES
1429 0 RVIA2 Definition layer: does not open all via conncetion, is shorted
1432 0 RVIA2 Definition layer: truncates via2, device shorted
1433 0 RVIA2 Definition layer : does not define a device
1437 0 RVIA2 Definition layer: over METRES
1445 0 RVIA3 Definition layer: does not open all via conncetion, is shorted
1448 0 RVIA3 Definition layer: truncates via3, device shorted
1449 0 RVIA3 Definition layer : does not define a device
1453 0 RVIA3 Definition layer: over METRES
1463 0 ERROR : POLY1 pin outside poly1
1464 0 ERROR : MET1 pin outside met1
1465 0 ERROR : MET2 pin outside met2
1467 0 ERROR : MET3 pin outside met3
1469 0 ERROR : MET4 pin outside met4
1470 0 ERROR : PAD pin outside pad metal
1485 0 NMOSRF_OPEN_GATE
1491 0 PMOSRF_OPEN_GATE
1501 0 NMOSRF Element rule : fixed length = 0.35
1508 0 PMOSRF Element rule : fixed length = 0.35
1511 0 NMOSRF Element Rule : Gate width must be 5.0 U or 10 U
1514 0 PMOSRF Element Rule : Gate width must be 5.0 U or 10 U
1522 0 NMOSRF Element rule stripe width 5 U : max width = 200 U
1524 0 NMOSRF Element rule stripe width 10 U : max width = 200 U
1532 0 PMOSRF Element rule stripe width 5 U : max width = 150 U
1534 0 PMOSRF Element rule stripe width 10 U : max width = 150 U
1537 0 VERT10_P2 Element Rule : Base Ntub Perimeter/4 = 13.8
1541 0 VERT10_P3 Element Rule : Ptap Inside Perimeter/4 = 14.9
1550 0 VERT10_E1 Element Rule : NTUB enclosure of ntap = 0.45
1552 0 LAT2_P1 Element Rule : Emitter Perimeter/4 = 2
1555 0 LAT2_P2 Element Rule : Collector net_pdiff Perimeter/4 = 6.2
1558 0 LAT2_P3 Element Rule : Base Ntub Perimeter/4 = 10.0
1562 0 LAT2_P4 Element Rule : Ptap Inside Perimeter/4 = 11.1
1569 0 LAT2_W1 Element Rule : Lateral Base Width = 1
1578 0 LAT2_E1 Element Rule : NTUB enclosure of ntap = 0.45
1583 0 LAT2_G1 Element Rule : gate of lat2 transistor not connected to VDD or VCC
1585 0 NMOSH_O1/NMOSMH_O1 Element Rule : Gate Overlap of Ntub = 1.6 U
1595 0 NMOSH_S1/NMOSMH_S1 Element Rule : Gate Drain Diff spacing = 2.8
1604 0 NMOSH_E1/NMOSMH_E1 Element Rule : Poly Extension of gate = 0.6 U
1611 0 NMOSH_L1/NMOSMH_L1 Element Rule : Gate Length = 3.0 U
1613 0 NMOSH_X1/NMOSMH_X1 Element Rule : drain angles = 45, 8 vertices
1615 0 NMOSH_X1/NMOSMH_X1 Element Rule : edge length = 0.6 * sqrt(2)
1624 0 CVART_MIN_W Element Rule : cvart min w length = 10.0
1625 0 CVARM_MIN_W Element Rule : cvarm min w length = 10.0
1626 0 CVART_MIN_L Element Rule : cvart min l length = 2.0
1627 0 CVART_MIN_L Element Rule : cvart min l length = 2.0
1634 0 CVAR_W1 Element Rule : Gate unit width = 0.65
1637 0 CVAR_L1 Element Rule : Gate unit length = 6.60
1646 0 CVAR_X1 Element Rule : Gate spacing 1.0
1656 0 CVAR_Y1 Element Rule : Diff spacing 1.6
1657 0 Illegal device : Zener diode must have 0.2 implant ovlp
1658 0 ZD2SM24_O1 Element Rule : must have 0.2 U implant ovlp
1665 0 ZD2SM24_W1 Element Rule : must have 0.40 U n-implant edge length
1666 0 ZD2SM24_W1 Element Rule : must have 0.40 U p-implant edge length
1689 0 PHDNWA850/PHDNWB850 : Illegal layer on photo diode
1692 0 PHDNWA850/PHDNWB850 : Illegal layer on photo diode : met4,via3
1708 0 PHDNWA850/PHDNWB850 : ntub must not enclose any other data
1709 0 PHDNWA850/PHDNWB850 : ntub does not enclose OPTDEF
1710 0 PHDNWA850/PHDNWB850 : OPTDEF does not cover ntub and ndiff totally
1711 0 PHDNWA850/PHDNWB850 : OPTDEF layer outside of ntub and ndiff
1713 0 PHDNWA850/PHDNWB850 : text label for light terminal (P) missing on top level of hierarchie , please add label with terminal name on layer DEVDEF opto for correct extraction
1719 0 PHR001 PHDNWA850/PHDNWB850 : Illegal layer on photo diode OPTDEF  poly1/poly2/met1/met2/met3/met4
1720 0 PHR001 PHDNWA850/PHDNWB850 : Illegal layer on photo diode  OPTDEF : met4
1726 0 BRR001 PHDNWB850 : Illegal layer on photo diode PAD_BARC  poly1/poly2/met1/met2/met3/met4
1727 0 BRR001 PHDNWB850 : Illegal layer on photo diode PAD_BARC : met4
1730 0 PHDNWB850 PAD_BARC : PAD_BARC not rectangle, ATTENTION : data prep problem also, cannot be scaled by 1.5 percent by side if no rect
1732 0 W1BR PHDNWB850 : Minimum PAD_BARC width = 5
1734 0 ILL_LAYER_CHIPEDGE chipedge is only used for testing purposes
1739 0 ATTENTION : Layer SFCDEF should not be used on design data for DRC checking, SFCDEF is a special definition layer for MASK Fabrication
1745 0 W2BR :  Maximum PAD_BARC width (1 PAD_BARC shape in design) = 150
1747 0 W3BR :  Maximum PAD_BARC width (multiple PAD_BARC shapes in design) = 50
1750 0 S1BRBR : Minimum PAD_BARC spacing = 7
1752 0 S1BRM1 : Minimum MET1 to PAD_BARC spacing = 1.1
1754 0 S1BRM2 : Minimum MET2 to PAD_BARC spacing = 1.4
1756 0 S1BRM3 : Minimum MET3 to PAD_BARC spacing = 1.6
1758 0 S1BRM4 : Minimum MET4 to PAD_BARC spacing = 2.3
1765 0 PHDNWA850/PHDNWB850 both on same design not allowed, different process option
1767 0 PHDNWA850 : PCOAT not allowed for this process
1768 0 PHDNWB850 : PCOAT not allowed for this process
1770 0 PHDNWA850_W1 : Minimum NTUB size (W and L) = 5
1771 0 PHDNWA850_W2 :  Maximum NTUB size (W and L) = 150
1775 0 PHDNWA850 W1/W2 : PHOTO diode is not square
2039 0 PHDNWA850_S1 : miss substrate ptap Fixed PDIFF to NTUB spacing = 0.4
2049 0 PHDNWA850_E1 : Fixed NTUB enclosure of NDIFF = 0.2
2056 0 PHDNWA850_S1 : Fixed PDIFF to NTUB spacing = 0.4
2059 0 PHDNWB850_W1 : Minimum PAD_BARC size (W and L) = 5
2060 0 PHDNWB850_W2 : Maximum PAD_BARC size (W and L) = 150
2064 0 PHDNWB850 W1/W2 : PHOTO diode is not square
2327 0 PHDNWB850_S1: miss substrate ptap Fixed PDIFF to NTUB spacing = 0.4
2337 0 PHDNWB850_E1 : Fixed NTUB enclosure of NDIFF = 0.2
2344 0 PHDNWB850_S1 : Fixed PDIFF to NTUB spacing = 0.4
2354 0 PHDNWB850_E2 : Fixed NDIFF enclosure of PAD_BARC = 0.5
2428 0 PHDNWB850_E2 : Fixed NDIFF enclosure of PAD_BARC = 0.5
2436 0 PHDNWB850_S2 : Fixed MET1 to PAD_BARC spacing = 1.2
2440 0 V1R003 : VIA1 overlapping SBDCON is not allowed
2442 0 S1COV1 : Minimum VIA1 spacing to SBDCON
2443 0 SBD5 DIODE : multiple SBDCON
2447 0 SDB5 DIODE : bad sbdcon
2454 0 SBD5_W DIODE fixed SBDCON width 0.4
2456 0 SBD5_W_L1 DIODE : SBDCON must have fixed L = 12 and fixed W = 0.4
2465 0 SBD5_X1 DIFF enclosure of SBDCON 0.3
2472 0 SBD5_X2 DIFF spacing 0.8
2479 0 SBD5_X3 DIFF spacing 0.55
2482 0 SBD5_X4 minimum NTUB ovlp ndiff 1.0
2486 0 SBD5_CATHODE_X5 SBD5_X5 minimum MET1 ovlp CONT 0.3
2490 0 SBD5_ANODE_X5 SBD5_X5 minimum MET1 ovlp CONT 0.3
2499 0 SBD5 DIODE : Illegal layer on Schottky diode
2527 0 SBD5_R1 : Multiple SBD5 in a shared NTUB shape must have the same orientation
2530 0 PFR001 : DEVDEF_pfuse outside IPDEF is not allowed
2531 0 Error : RESDEF over DEVDEF_pfuse not allowed
2538 0 ERC Warning : This poly2 over HRES layer is high ohmic, but shorted for LVS
2539 0 CPMIM not supported over RFDEF
2545 0 CPMIM error : cpmim must be totally inside POLY2
2554 0 E1P2MC : Fixed poly2 enclosure of metcap 1.15
2556 0 CPMIM_R1 : CPMIM overlapping MET1 is not allowed
2569 0 CPMIM_R2 Element check: met3 metcap/poly1 plates of CPMIM not connected correctly
2570 0 CPMIM_R3 Element check: met2/poly2 plates of CPMIM not connected correctly
2572 0 W1PW : Minimum FIDEF width = 1.7
2575 0  S1PWPW : Minimum FIDEF spacing = 1
2578 0 S1NWPW : Minimum FIDEF to NTUB spacing = 6.5
2581 0 S1HVHV Minimum HVDEF spacing = 0.1
2583 0 HVR001 Each HVDEF shape must be marked with a single HVDEF text label
2588 0 HVR001 : Version of NMOS18T_REV1 obsolete
2589 0 HVR001 : Version of NMOS30M_REV2 obsolete
2590 0 HVR001 : No HVDEF on NMOS18T
2591 0 HVR001 : No HVDEF on NMOS30M
2592 0 HVR001 : Version of NMOS18T obsolete or missing
2593 0 HVR001 : Version of NMOS30M obsolete or missing
2594 0 HVR001 : HVDEF has illegal name on NMOS18T
2595 0 HVR001 : HVDEF has illegal name on NMOS30M
2620 0 NMOS18T/NMOS30M L Element Rule : Min gate length = 0.5 U
2621 0 NMOS18T/M W2 Element Rule : Min gate width/2 = 5 U
2634 0 NMOS30M X4 Element Rule : drain ndiff to source diff spacing (field plate) 2.0 U fixed
2641 0 NMOS18T X4 Element Rule : drain ndiff to source diff spacing (field plate) 1.8 U fixed
2650 0 NMOS30M X1 Element Rule : poly1 to drain diff spacing 0.4 U fixed
2657 0 NMOS18T X1 Element Rule : poly1 to drain diff spacing 0.35 U fixed
2667 0 NMOS30M/NMOS18T Element Rule X3 : ntub ovlp drain diff 1.85 U fixed
2676 0 NMOS30M Element Rule X5 : source diff ovlp of fidef = 1.5
2683 0 NMOS18T Element Rule X5 : source diff ovlp of fidef = 1.8
2690 0 NMOS30M/T Element Rule Y1 : poly1 to drain diff spacing 1 U fixed
2708 0 NMOS30M/T Element Rule Y2 : ntub stripe ovlp of drain diff = 3 
2714 0 NMOS18T/M Y3 Element Rule : poly width of gate connect = 2 U
2721 0 NMOS30M/T Element Rule Y4 : fidef ovlp of ntub = 2.8 U
2722 0 NMOS18T/M  Element Rule : nmos30m/nmos18t must have 1 ntub shape
2728 0 NMOS30M/T Element Rule Y5 : fidef to bulk pdiff spacing = 1.2 
2730 0 NMOS18T/M Y8 Element Rule : poly must be angled
2732 0 NMOS18T/M Y8 Element Rule : 45 degree poly must have length 0.7
2734 0 NMOS18T/M Y9 Element Rule : 45 degree poly must have length 0.7
2736 0 NMOS18T/M Y11 Element Rule : fidef must be angled
2738 0 NMOS18T/M Y11 Element Rule : fidef edge length = 0.75 * sqrt(2)
2742 0 NMOS18T/M Element Rule Y10 : fidef vertex to sdiff spacing = 1.75
2744 0 W2PW : Minimum PFIMP width = 0.8
2747 0  S2PWPW : Minimum PFIMP spacing = 1
2749 0 PWR002 : (PFIMP and not (HVDEF or SFCDEF)) is not allowed
2761 0 HVR001 : No HVDEF on PMOSD30M
2762 0 HVR001 : Version of PMOSD30M obsolete or missing
2763 0 HVR001 : Version of PMOSD30M is REV1 and obsolete, use rev2 
2764 0 HVR001 : HVDEF has illegal name on PMOSD30M
2783 0 PMOSD30M : Minimum CHANNEL length = 0.6
2784 0 PMOSD30M : Minimum CHANNEL width / N = 6.4
2797 0 PMOSD30M X1 Element Rule : POLY1 to DRAIN-PDIFF spacing = 0.3
2804 0 PMOSD30M Element Rule Y1 : POLY1 to DRAIN-PDIFF spacing = 0.3
2811 0 PMOSD30M X2 Element Rule : DRAIN-PDIFF to SOURCE-DIFF spacing (field plate) = 2.4
2818 0 PMOSD30M_X3 Element Rule : PFIMP overlap of SOURCE-DIFF = 0.6
2821 0 PMOSD30M_X4 Element Rule : Minimum NTUB enclosure of BULK-NDIFF = 0.8
2823 0 PMOSD30M_X5 Element Rule : NTUB to SUBSTRATE-PDIFF spacing = 2.4
3135 0 PMOSD30M_X5 Element Rule : miss substrate ptap Fixed PDIFF to NTUB spacing = 2.4
3151 0 PMOSD30M Element Rule X5  : bad layer between ntub and subtap
3159 0 PMOSD30M Element Rule X6 : NPLUS to PGATE spacing = 0.3
3168 0 PMOSD30M Element Rule Y2 : PFIMP enclosure of DRAIN-PDIFF = 2
3175 0 PMOSD30M Element Rule Y3 : BULK-NDIFF to DRAIN-PDIFF spacing = 4.25
3181 0 PMOSD30M Element Rule Y4 : POLY1 width of gate connection = 1.75
3183 0 PMOSD30M Element Rule Y5 : illegal vertices POLY1 45-deg corner (outside) = 0.55
3185 0 PMOSD30M Element Rule Y5 : POLY1 45-deg corner (outside) = 0.55
3189 0 PMOSD30M Element Rule Y5 : poly hole must not be angled 
3194 0 PMOSD30M Element Rule Y8 : Minimum PPLUS enclosure of PDIFFCON = 0.2
3208 0 PMOSD30M_R2 Element Rule R2 : SOURCE-PDIFF cannot be butted with BULK-NDIFF ring
3209 0 PMOSD30M_R2 Element Rule R2 : SOURCE-PDIFF cannot be butted with BULK-NDIFF ring
3215 0 PMOSD30M Element Rule Y7 : Minimum PDIFF enclosure of PDIFFCON = 0.2
3217 0 PMOSD30M Element Rule Y7: fixed size of butting ndiff square 0.9 x 0.9
3220 0 PMOSD30M INFO : min spacing of butting ndiff to ndiff 1.6 U
3239 0 PMOSD30M_R1: Bulk and source must be connected with met1 (check1)
3255 0 PMOSD30M_R1: Bulk and source must be connected with met1 (check2)
3274 0 PMOSD30M_R1: Bulk and source must be connected with met1 also for single device
3285 0 PMOSD30M_HVR003_sources_must_be_connected_together
3291 0 PMOSD30M Element Rule : pfimp must be rectangle
3292 0  PMOSD30M : this device not supported for any pad over active application
3304 0 HVR001 : No HVDEF on PMOS30M
3305 0 HVR001 : Version of PMOS30M obsolete or missing
3306 0 HVR001 : HVDEF has illegal name on PMOS30M
3325 0 PMOS30M : _PMOS30M_L_
3326 0 PMOS30M : _PMOS30M_W2_
3339 0 PMOS30M X1 Element Rule : _PMOS30M_X1_
3346 0 PMOS30M Element Rule Y1 : _PMOS30M_Y1_
3353 0 PMOS30M X2 Element Rule : _PMOS30M_X2_
3360 0 PMOS30M_X3 Element Rule : _PMOS30M_X3_
3363 0 PMOS30M_X4 Element Rule : _PMOS30M_X4_
3365 0 PMOS30M_X5 Element Rule : _PMOS30M_X5_
3677 0 PMOS30M_X5 Element Rule : miss substrate ptap Fixed PDIFF to NTUB spacing = 2.4
3693 0 PMOS30M Element Rule X5  : bad layer between ntub and subtap
3702 0 PMOS30M Element Rule Y2 : _PMOS30M_Y2_
3709 0 PMOS30M Element Rule Y3 : _PMOS30M_Y3_
3715 0 PMOS30M Element Rule Y4 : _PMOS30M_Y4_
3717 0 PMOS30M Element Rule Y5 : illegal vertices _PMOS30M_Y5_
3719 0 PMOS30M Element Rule Y5 : _PMOS30M_Y5_
3723 0 PMOS30M Element Rule Y5 : poly hole must not be angled 
3734 0 PMOS30M_HVR003_sources_must_be_connected_together
3740 0 PMOS30M Element Rule : pfimp must be rectangle
3741 0  PMOS30M : this device not supported for any pad over active application
3745 0 HVR001 : Version of ESDPD12 obsolete or missing
3746 0 HVR001 : HVDEF has illegal name on ESDPD12
3750 0 HVR001 : Version of ESDPD26 obsolete or missing
3751 0 HVR001 : HVDEF has illegal name on ESDPD26
3755 0 HVR001 : Version of ESDPD18 obsolete or missing
3756 0 HVR001 : HVDEF has illegal name on ESDPD18
3760 0 HVR001 : Version of ESDPD30 obsolete or missing
3761 0 HVR001 : HVDEF has illegal name on ESDPD30
3765 0 HVR001 : Version of ESDGCN5 obsolete or missing
3766 0 HVR001 : HVDEF has illegal name on ESDGCN5
3770 0 HVR001 : Version of ESDGCP5 obsolete or missing
3771 0 HVR001 : HVDEF has illegal name on ESDGCP5
3775 0 HVR001 : Version of ESDFDP5 obsolete or missing
3776 0 HVR001 : HVDEF has illegal name on ESDFDP5
3780 0 HVR001 : Version of ESDFDN5 obsolete or missing
3781 0 HVR001 : HVDEF has illegal name on ESDFDN5
3783 0 HVR001 : HVDEF does not enclose a valid HV-device, bad HVDEF or bad device
3802 0 ESDPD12_L Element Rule : _ESDPD12_L_
3803 0 ESDPD12_W1 Element Rule : _ESDPD12_W1_
3804 0 ESDPD12_W2 Element Rule : _ESDPD12_W2_
3813 0 ESDPD12_X2 Element Rule : _ESDPD12_X2_
3822 0 ESDPD12_Y2 Element Rule : _ESDPD12_Y2_
3829 0 ESDPD12_X3 Element Rule : _ESDPD12_X3_
3836 0 ESDPD12_Y3 Element Rule : _ESDPD12_Y3_
3843 0 ESDPD12_X4 Element Rule : _ESDPD12_X4_
3858 0 ESDPD18_L Element Rule : CATHODE-NTUB length = 1.7
3859 0 ESDPD18_W1 Element Rule : Minimum CATHODE-NTUB width = 10
3860 0 ESDPD18_W2 Element Rule : Maximum CATHODE-NTUB width = 10000
3869 0 ESDPD18_X2 Element Rule : NTUB enclosure of NDIFF = 0.5
3878 0 ESDPD18_Y2 Element Rule : NTUB enclosure of NDIFF = 1.5
3885 0 ESDPD18_X3 Element Rule : PDIFF to NTUB spacing = 0.5
3892 0 ESDPD18_Y3 Element Rule : PDIFF to NTUB spacing = 2
3899 0 ESDPD18_X4 Element Rule : PDIFF width = 0.7
3902 0 ESDPD18_X5 Element Rule : Minimum CATHODE-MET1 width = 1.6
3919 0 ESDPD26_L Element Rule : CATHODE-NTUB length = 2.1
3920 0 ESDPD26_W1 Element Rule : Minimum CATHODE-NTUB width = 10
3921 0 ESDPD26_W2 Element Rule : Maximum CATHODE-NTUB width = 10000
3930 0 ESDPD26_X2 Element Rule : NTUB enclosure of NDIFF = 0.7
3939 0 ESDPD26_Y2 Element Rule : NTUB enclosure of NDIFF = 1.7
3946 0 ESDPD26_X3 Element Rule : PDIFF to NTUB spacing = 1
3953 0 ESDPD26_Y3 Element Rule : PDIFF to NTUB spacing = 2
3960 0 ESDPD26_X4 Element Rule : PDIFF width = 0.7
3963 0 ESDPD26_X5 Element Rule : Minimum CATHODE-MET1 width = 1.9
3980 0 ESDPD30_L Element Rule : CATHODE-NTUB length = 2.3
3981 0 ESDPD30_W1 Element Rule : Minimum CATHODE-NTUB width = 10
3982 0 ESDPD30_W2 Element Rule : Maximum CATHODE-NTUB width = 10000
3991 0 ESDPD30_X2 Element Rule : NTUB enclosure of NDIFF = 0.8
4000 0 ESDPD30_Y2 Element Rule : NTUB enclosure of NDIFF = 1.8
4007 0 ESDPD30_X3 Element Rule : PDIFF to NTUB spacing = 1.5
4014 0 ESDPD30_Y3 Element Rule : PDIFF to NTUB spacing = 2
4021 0 ESDPD30_X4 Element Rule : PDIFF width = 0.7
4024 0 ESDPD30_X5 Element Rule : Minimum CATHODE-MET1 width = 1.9
4039 0 ESDFDP5_L Element Rule : ANODE-PDIFF length = 0.7
4040 0 ESDFDP5_W1 Element Rule : Minimum ANODE-PDIFF width = 10
4041 0 ESDFDP5_W2 Element Rule : Maximum ANODE-PDIFF width = 200
4048 0 ESDFDP5_X2 Element Rule : PDIFF to NDIFF spacing = 0.7
4055 0 ESDFDP5_X3 Element Rule : NDIFF width = 0.7
4068 0 ESDFDN5_L Element Rule : CATHODE-NDIFF length = 0.7
4069 0 ESDFDN5_W1 Element Rule : Minimum CATHODE-NDIFF width = 10
4070 0 ESDFDN5_W2 Element Rule : Maximum CATHODE-NDIFF width = 200
4077 0 ESDFDN5_X2 Element Rule : NDIFF to PDIFF spacing = 0.7
4084 0 ESDFDN5_X3 Element Rule : PDIFF width = 0.7
4110 0 ESDGCN5_L Element Rule : CATHODE-NDIFF length = 0.7
4111 0 ESDGCN5_W1 Element Rule : Minimum CATHODE-NDIFF width = 0.7
4112 0 ESDGCN5_W2 Element Rule : Maximum CATHODE-NDIFF width = 100
4119 0 ESDGCN5_X2 Element Rule : NDIFF to PDIFF spacing = 0.7
4126 0 ESDGCN5_X3 Element Rule : PDIFF width = 0.7
4154 0 ESDGCP5_L Element Rule : ANODE-PDIFF length = 0.7
4155 0 ESDGCP5_W1 Element Rule : Minimum ANODE-PDIFF width = 0.7
4156 0 ESDGCP5_W2 Element Rule : Maximum ANODE-PDIFF width = 100
4163 0 ESDGCP5_X2 Element Rule : PDIFF to NDIFF spacing = 0.7
4170 0 ESDGCP5_X3 Element Rule : NDIFF width = 0.7
4178 0 MOSW : Waffle trans : cannot mix different size of holes over same diff
4180 0 MOSW : Waffle trans hole : poly hole size incorrect
4186 0 MOSW : Waffle trans gate : these gates cannot be identified correctly due to size of poly hole and are discarded from LVS
4194 0 NMOSW : Waffle trans : shorted device nmosw
4202 0 NMOSMW : Waffle trans : shorted device nmosmw
4210 0 PMOSW : Waffle trans : shorted device pmosw
4218 0 PMOSMW : Waffle trans : shorted device pmosmw
4238 0 NMOSW : Waffle trans : s/d of waffle trans not connected to other sd over same waffle diff, Inactive Unit found, causes encreasing current flow in neighbouring devices
4258 0 NMOSMW : Waffle trans : s/d of waffle trans not connected to other sd over same waffle diff, Inactive Unit found, causes encreasing current flow in neighbouring devices
4278 0 PMOSW : Waffle trans : s/d of waffle trans not connected to other sd over same waffle diff, Inactive Unit found, causes encreasing current flow in neighbouring devices
4298 0 PMOSMW : Waffle trans : s/d of waffle trans not connected to other sd over same waffle diff, Inactive Unit found, causes encreasing current flow in neighbouring devices
4301 0  NMOSW for waffle trans we expect 1, 2, or 4 s/d conts
4304 0  NMOSMW for waffle trans we expect 1, 2, or 4 s/d conts
4315 0 NMOSW_W : Waffle trans : fixed channel length 4 = 2.8 sqrt(2)
4316 0 NMOSW_L1 : Waffle trans : min channel length 0.5 = 0.35 sqrt(2)
4317 0 NMOSW_L2 : Waffle trans : max channel length 3.0 = 2.1 sqrt(2)
4318 0 NMOSMW_W : Waffle trans : fixed channel length 4 = 2.8 sqrt(2)
4319 0 NMOSMW_L1 : Waffle trans : min channel length 0.5 = 0.35 sqrt(2)
4320 0 NMOSMW_L2 : Waffle trans : max channel length 3.0 = 2.1 sqrt(2)
4340 0 NMOSW_S1 : Waffle trans : fixed diffcon to gate spacing 1.2 0.85 * sqrt(2)
4360 0 NMOSMW_S1 : Waffle trans : fixed diffcon to gate spacing 1.2 0.85 * sqrt(2)
4363 0  PMOSW for waffle trans we expect 1, 2, or 4 s/d conts
4366 0  PMOSMW for waffle trans we expect 1, 2, or 4 s/d conts
4377 0 PMOSW_W : Waffle trans : fixed channel length 4 = 2.8 sqrt(2)
4378 0 PMOSW_L1 : Waffle trans : min channel length 0.5 = 0.35 sqrt(2)
4379 0 PMOSW_L2 : Waffle trans : max channel length 3.0 = 2.1 sqrt(2)
4380 0 PMOSMW_W : Waffle trans : fixed channel length 4 = 2.8 sqrt(2)
4381 0 PMOSMW_L1 : Waffle trans : min channel length 0.5 = 0.35 sqrt(2)
4382 0 PMOSMW_L2 : Waffle trans : max channel length 3.0 = 2.1 sqrt(2)
4402 0 PMOSW_S1 : Waffle trans : fixed diffcon to gate spacing 1.2 0.85 * sqrt(2)
4422 0 PMOSMW_S1 : Waffle trans : fixed diffcon to gate spacing 1.2 0.85 * sqrt(2)
4423 0 ILL_LAYER_LVTA
4424 0 ILL_LAYER_LVPTUB
4427 0 ILL_ELEMENT_RPOLYH_RPOLYZ
4430 0 ILL_ELEMENT_RPOLY2P_RPOLY2PH
4431 0 NTUB net layer must not be used in layout view
4432 0 POLY1 net layer must not be used in layout view
4433 0 POLY2 net layer must not be used in layout view
4434 0 CONT net layer must not be used in layout view
4435 0 MET1 net layer must not be used in layout view
4436 0 VIA1 net layer must not be used in layout view
4437 0 MET2 net layer must not be used in layout view
4438 0 VIA2 net layer must not be used in layout view
4439 0 MET3 net layer must not be used in layout view
4440 0 VIA3 net layer must not be used in layout view
4441 0 MET4 net layer must not be used in layout view
4443 0 Warning: No MET4 on MET4 Pin
4445 0 Warning: No POLY1 on POLY1 Pin
4447 0 Warning: No MET1 on MET1 Pin
4449 0 Warning: No MET2 on MET2 Pin
4451 0 Warning: No MET3 on MET3 Pin
4460 0 REC002 REC002 NTUB not multiple 45 degrees REC002
4461 0 REC002 REC002 DIFF not multiple 45 degrees REC002
4462 0 REC002 REC002 MIDOX not multiple 45 degrees REC002
4463 0 REC002 REC002 POLY1 not multiple 45 degrees REC002
4464 0 REC002 REC002 NPLUS not multiple 45 degrees REC002
4465 0 REC002 REC002 PPLUS not multiple 45 degrees REC002
4466 0 REC002 REC002 HRES not multiple 45 degrees REC002
4467 0 REC002 REC002 CONT not multiple 45 degrees REC002
4468 0 REC002 REC002 MET1 not multiple 45 degrees REC002
4469 0 REC002 REC002 VIA1 not multiple 45 degrees REC002
4470 0 REC002 REC002 MET2 not multiple 45 degrees REC002
4471 0 REC002 REC002 VIA2 not multiple 45 degrees REC002
4472 0 REC002 REC002 MET3 not multiple 45 degrees REC002
4473 0 REC002 REC002 VIA3 not multiple 45 degrees REC002
4474 0 REC002 REC002 MET4 not multiple 45 degrees REC002
4475 0 REC002 REC002 PAD not multiple 45 degrees REC002
4489 0 NW_W_1 Minimum NTUB width = 1.7
4491 0 NW_W_2 Minimum HOT_NTUB width = 3
4505 0 NW_S_1 Minimum spacing of NTUB with different potential = 3
4508 0 NW_S_2 Minimum spacing of NTUB with same potential = 1
4510 0 NW_S_2 Minimum spacing of NTUB with same potential = 1 notch
4523 0 OD_W_1 Minimum DIFF width to define the width of NMOS/PMOS = 0.4 ngate
4532 0 OD_W_1 Minimum DIFF width to define the width of NMOS/PMOS = 0.4 pgate
4534 0 OD_W_2 Minimum DIFF width for interconnection (NDIFF or PDIFF) = 0.3
4537 0 OD_S_1 Minimum DIFF spacing = 0.6
4539 0 OD_S_1 Minimum DIFF spacing = 0.6 notch 
4545 0 OD_C_1 Minimum NTUB enclosure of NDIFF = 0.2
4549 0 OD_C_2 Minimum NDIFF to NTUB spacing = 1.2
4564 0 OD_C_3 Minimum NDIFF to HOT_NTUB spacing (no PTAP in between) = 2.6
4568 0 OD_C_4 Minimum NTUB enclosure of PDIFF = 1.2
4570 0 OD_C_5 Minimum PDIFF to NTUB spacing = 0.2
4573 0 OD_C_6a Minimum PDIFF to NGATE spacing = 0.45
4578 0 OD_C_6b Minimum NDIFF to PGATE spacing = 0.45
4586 0 OD_S_2B Minimum NDIFF to non-butting PDIFF spacing = 0.6
4590 0 INFO: DIFF missing nplus/pplus
4592 0 W1XM Minimum MIDOX width = 0.6
4600 0 OD2_E_1 Minimum MIDOX enclosure of DIFF = 0.6
4603 0 OD2_S_1 Minimum MIDOX spacing = 0.6
4605 0 OD2_C_1 Minimum MIDOX to DIFF spacing = 0.6
4607 0 BAD1XM MIDOX outside GATE is not allowed
4619 0 PO_W_1a Minimum GATE length of PMOS = 0.35
4621 0 PO_W_1b Minimum GATE length of PMOSM = 0.5
4623 0 PO_W_2a Minimum GATE length of NMOS = 0.35
4625 0 PO_W_2b Minimum GATE length of NMOSM = 0.5
4628 0 PO_W_3 Minimum POLY1 width for interconnect = 0.35
4631 0 PO_S_1 Minimum POLY1 spacing = 0.45 
4633 0 PO_S_1 Minimum POLY1 spacing = 0.45 notch
4635 0 PO_C_1 Minimum POLY1 to DIFF spacing = 0.2
4644 0 PO_C_2 Minimum DIFF extension of GATE = 0.5
4647 0 PO_O_1 Minimum POLY1 extension of GATE = 0.4
4649 0 PO2_W_1 Minimum CPOLY width = 0.8
4652 0 PO2_S_1 Minimum CPOLY spacing = 0.65
4655 0 PO2_E_1 Minimum POLY1 enclosure of CPOLY = 1
4658 0 PO2_E_2 Minimum CPOLY enclosure of POLY2CON = 0.6
4660 0 PO2_C_1 Minimum POLY1CON to CPOLY spacing = 1.2
4662 0 PO2_W_2 Minimum POLY2 width = 0.65
4665 0 PO2_S_2 Minimum POLY2 spacing = 0.5
4667 0 PO2_S_2 Minimum POLY2 spacing = 0.5 notch
4669 0 PO2_S_2 Minimum POLY2 spacing = 0.5 notch
4671 0 PO2_S_2 Minimum POLY2 spacing = 0.5 notch
4673 0 PO2_W_3 Minimum RPOLYH width = 0.8
4676 0 PO2_S_3 Minimum RPOLYH spacing = 0.75
4678 0 PO2_S_3 Minimum RPOLYH spacing = 0.75 notch
4680 0 PO2_C_2 Minimum DIFF to POLY2 spacing = 0.2
4682 0 PO2_C_3 Minimum POLY1 to POLY2 spacing = 0.65
4687 0 PO2_E_3 Minimum POLY2 enclosure of POLY2CON = 0.25
4688 0 PO2_R_1 POLY2 on DIFF is not allowed
4690 0 PP_W_1 Minimum PPLUS width = 0.6
4693 0 PP_S_1 Minimum PPLUS spacing = 0.6
4695 0 PP_C_1 Minimum PPLUS to DIFF spacing = 0.35
4697 0 PP_C_2 Minimum PPLUS to NGATE spacing = 0.45
4703 0 PP_C_3 Minimum PPLUS extension of PGATE = 0.45
4705 0 PP_O_1  Minimum overlap of PPLUS and DIFF = 0.45
4708 0 PP_E_1 Minimum PPLUS extension of DIFF = 0.25
4715 0 PP_C_5 NP_C_5 NPC5/PPC5  Minimum PPLUS to NPLUS spacing on POLY1 = 0.25
4717 0 PP_C_6 Minimum PPLUS to NPLUS spacing on DIFF with same potential = 0
4719 0 NP_W_1 Minimum NPLUS width = 0.6
4722 0 NP_S_1 Minimum NPLUS spacing = 0.6
4724 0 NP_C_1 Minimum NPLUS to DIFF spacing = 0.35
4728 0 NP_C_2 Minimum NPLUS to PGATE spacing = 0.45
4731 0 NP_C_3 Minimum NPLUS extension of NGATE = 0.45
4733 0 NP_O_1  Minimum overlap of NPLUS and DIFF = 0.45
4736 0 NP_E_1 Minimum NPLUS extension of DIFF = 0.25
4738 0 NP_C_6 Minimum NPLUS to PPLUS spacing on DIFF with same potential = 0
4746 0 CO_W_1 Fixed CONT width = 0.4
4749 0 CO_S_1 Minimum CONT spacing = 0.4
4751 0 CO_C_1 Minimum DIFFCON to GATE spacing = 0.3
4753 0 CO_C_2  Minimum POLY1CON to DIFF spacing = 0.4
4756 0 CO_E_1 Minimum DIFF enclosure of DIFFCON = 0.15
4759 0 CO_E_2 Minimum POLY1 enclosure of POLY1CON = 0.2
4764 0 CO_E_3 Minimum PPLUS enclosure of PDIFFCON = 0.25
4767 0 CO_E_4  Minimum NPLUS enclosure of NDIFFCON = 0.25
4768 0 CO_R_1 POLY1CON on DIFF is not allowed
4771 0 CO_R_2 Butted CONT is not allowed
4772 0 R0_1_CT CONT without DIFF or POLY1 or POLY2 is not allowed
4774 0 M1_W_1 Minimum MET1 width = 0.5
4777 0 M1_S_1  Minimum MET1 spacing = 0.45
4820 0 M1_S_2 Minimum MET1 to WIDE_MET1 spacing = 0.8 wide wide
4822 0 M1_S_2 Minimum MET1 to WIDE_MET1 spacing = 0.8 wide small
4827 0 M1_E_1 Minimum MET1 enclosure of CONT = 0.15
4829 0 VIA1_W_1 Fixed VIA1 width = 0.5
4832 0 VIA1_S_1 Minimum VIA1 spacing = 0.45
4837 0 VIA1_E_1 Minimum MET1 enclosure of VIA1 = 0.2
4838 0 R01V1 VIA1 without MET1 is not allowed
4840 0 M2_W_1 Minimum MET2 width = 0.6
4843 0 M2_S_1 Minimum MET2 spacing = 0.5
4886 0 M2_S_2 Minimum MET2 to WIDE_MET2 spacing = 0.8 wide wide
4888 0 M2_S_2 Minimum MET2 to WIDE_MET2 spacing = 0.8 wide small
4893 0 M2_E_1 Minimum MET2 enclosure of VIA1 = 0.15
4895 0 VIA2_W_1 Fixed VIA2 width = 0.5
4898 0 VIA2_S_1 Minimum VIA2 spacing = 0.45
4903 0 VIA2_E_1 Minimum MET2 enclosure of VIA2 = 0.2
4904 0 R01V2 VIA2 without MET2 is not allowed
4906 0 M3_W_1  Minimum MET3 width = 0.6
4909 0 M3_S_1 Minimum MET3 spacing = 0.5
4914 0 M3_E_1 Minimum MET3 enclosure of VIA2 = 0.15
4957 0 M3S2 Minimum MET3 to WIDE_MET3 spacing = 0.8 wide wide 
4959 0 M3_S_2 Minimum MET3 to WIDE_MET3 spacing = 0.8 wide small
4961 0 VIA3_W_1 Fixed VIA3 width = 0.5
4964 0 VIA3_S_1 Minimum VIA3 spacing = 0.45
4969 0 VIA3_E_1 Minimum MET3 enclosure of VIA3 = 0.2
4970 0 R01V3 VIA3 without MET3 is not allowed
4972 0 M4_W_1 Minimum MET4 width = 0.6
4975 0 M4_S_1 Minimum MET4 spacing = 0.6
4980 0 M4_E_1 Minimum MET4 enclosure of VIA3 = 0.15
5023 0 M4_S_2 Minimum MET4 to WIDE_MET4 spacing = 0.8 wide wide
5025 0 M4_S_2 Minimum MET4 to WIDE_MET4 spacing = 0.8 wide small
5030 0 CBR1 CB_R_1 missing met1
5032 0 CBR1 CB_R_1 missing met2
5034 0 CBR1 CB_R_1 missing met3
5037 0 CBR1 CB_R_1 missing met4
5038 0 ERC Warning: Missing top met4 on Test or Probe pad
5040 0 W1PA Minimum PAD width = 15
5042 0 CB_W_1 Minimum bonding PAD width (85um preferred, 60um on request) = 70
5044 0 CB_W_1_G1 Minimum bonding PAD width (85um preferred, 60um on request) = 70 preferred 85
5047 0 CB_S_1 Minimum PAD spacing = 15
5051 0 CB_E_1 Minimum MET1 enclosure of PAD_ST = 5
5055 0 CB_E_2 Minimum MET2 enclosure of PAD_3OA = 5
5058 0 CB_E_3 Minimum MET3 enclosure of PAD = 5
5061 0 CB_E_4 Minimum MET4 enclosure of PAD = 5
5080 0 CB_E_5 Minimum MET1 enclosure of the nearest PADVIA1 = 3
5123 0 CB_E_5 bad diamond shape of pad via array must have 4 corners
5126 0 CB_E_5 bad diamond shape of pad via array
5127 0 CB_E_7 bad diamond shape of padvia2 array must have 4 corners
5130 0 CB_E_7 bad diamond shape of padvia2 array
5141 0 CB_E_9 bad diamond shape of padvia3 array must have 4 corners
5144 0 CB_E_9 bad diamond shape of padvia3 array
5147 0 CB_E_7 Minimum MET2 enclosure of the nearest PADVIA2 and PADVIA1 = 3 padvia1
5150 0 CB_E_7 Minimum MET2 enclosure of the nearest PADVIA2 and PADVIA1 = 3 padvia2
5153 0 CB_E_9  Minimum MET3 enclosure of the nearest PADVIA3 and PADVIA2 = 3
5156 0 CB_E_9 Minimum MET3 enclosure of the nearest PADVIA3 and PADVIA2 = 3
5159 0 CB_E_11 Minimum MET4 enclosure of the nearest PADVIA3 = 3
5162 0 CB_S_2 Minimum PADVIA1 spacing = 0.8
5165 0 CB_S_3 Minimum PADVIA2 spacing = 0.8
5168 0 CB_S_4 Minimum PADVIA3 spacing = 0.8
5170 0 CB_C_1 Minimum PADVIA2 to PADVIA1 spacing = 0.3
5172 0 CB_C_2 Minimum PADVIA3 to PADVIA2 spacing = 0.3
5174 0 CB_R_2 Minimum ratio of PADVIA1 area to PAD_ST area [%] = 5
5176 0 CB_R_3 Minimum ratio of PADVIA2 area to PAD_ST area [%] = 5
5178 0 CB_R_4 Minimum ratio of PADVIA3 area to PAD_ST area [%] = 5
5179 0 CB_C_1 Illegal pad via stack via1/via2
5180 0 CB_C_2 Illegal pad via stack via2/via3
5185 0 S1DFPA Minimum PAD_ST to DIFF spacing = 9
5187 0 S1P1PA Minimum PAD_ST to POLY1 spacing = 9
5189 0 S1P2PA Minimum PAD_ST to POLY2 spacing = 9
5192 0 S1M1PA Minimum PAD_ST to MET1 spacing (different net) = 9
5195 0 S1M2PA Minimum PAD_ST to MET2 spacing (different net) = 9
5198 0 S1M3PA Minimum PAD_ST to MET3 spacing (different net) = 9
5201 0 S1M4PA Minimum PAD_ST to MET4 spacing (different net) = 9
5202 0 R01PA PAD without MET4 is not allowed
5203 0 TOPOLOGY PROBLEM : POA pad met 4 stack found, but totally enclosed by MET1
5206 0 Illegal POA pad met3 stack for 4 metal process
5208 0 TOPOLOGY PROBLEM : POA pad met 4 stack found, but totally enclosed by MET2
5210 0 CB_W_1_G1 Minimum bonding PAD width (85um preferred, 60um on request) = 70 Min bonding pad width 70 U, 85 U preferred, 60 U request
5212 0 CB_W_1_G1 Minimum bonding PAD width (85um preferred, 60um on request) = 70 Min bonding pad width 70 U, 85 U preferred, 60 U request
5214 0 CB_W_1_G1 Minimum bonding PAD width (85um preferred, 60um on request) = 70 Min bonding pad width 70 U, 85 U preferred, 60 U request
5215 0 PAR006 : PAD_4OA overlapping VIA2 is not allowed
5218 0 S2PAV2 : Minimum PAD_4OA to VIA2 spacing = 0.5
5221 0 S1PAV3 : Minimum PAD_4OA to VIA3 spacing = 0.25
5225 0 E1PAV3 Minimum PAD_4OA enclosure of VIA3 = 0.2
5233 0 PAR007 : (PAD_4OA sized by -0.7) overlapping VIA3 is not allowed
5235 0 PAR002 KEPOUT definition : (PAD_4OA AND KEPOUT) is not allowed
5238 0 S2KOPA KEPOUT definition : Minimum spacing PAD_4OA to (KEPOUT or SFCDEF) = 7
5244 0 S2M3PA Minimum PAD_4OA to MET3 spacing (different net) = 7
5247 0 S2M4PA Minimum PAD_4OA to MET4 spacing (different net) = 7
5248 0 PAR010 : PAD_OA overlapping CPOLY is not allowed
5299 0 PAR008 Density : Line-of-sight looking through all VIA3 rows at any angle must be blocked by at least one VIA3,via3 density probably too small for this rule
5328 0 PAR008 Density : use 1 row of via3 at min ovlp of PAD poa
5346 0 PAR008 : Line-of-sight looking through all VIA3 rows at any angle must be blocked by at least one VIA3
5392 0 PAR009 :  LV_GATE L > 0.5 PAD_OA overlapping GATE is not allowed,  No valid exemption for LV_GATE, L > 0.5
5398 0 PAR009 : LV_GATE L=LMIN W < 400  PAD_OA overlapping GATE is not allowed, No valid exemption for LV_GATE, L <= 0.5, but total W < 400 U
5431 0  PAR009 : NMOS30M/NMOS18T  L > LMIN  PAD_OA overlapping GATE is not allowed,  No valid exemption for HV_GATE, L > 0.5 LMIN
5446 0 PAR009 : NMOS30M/NMOS18T  L=LMIN W < 400 PAD_OA overlapping GATE is not allowed, No valid exemption for HV_GATE, L <= 0.5 LMIN, but total W < 400 U
5474 0 PAR009 : NMOSH  L > LMIN  PAD_OA overlapping NMOSH_GATE is not allowed,  No valid exemption for NMOSH GATE, L > 3.0
5480 0 PAR009 : NMOSH  L = LMIN < 400 PAD_OA overlapping NMOSH_GATE is not allowed, No valid exemption for NMOSH__GATE, L <= 3.0, but total W < 400 U
5498 0 PAR009: PAD_4OA overlapping GATE is not allowed,  Exemptions : HV_GATE  with HVDEF text ESD*/ LV_GATE L <= 0.5, total active trans W >= 400/ HV_GATE L = MIN, total active trans W >= 400 / LV_GATE overlapping holed POLY1 ..waffel trans
5500 0 W1HR Minimum HRES width = 0.6
5503 0 S1HRHR Minimum HRES spacing = 0.6
5504 0 BAD1HR HRES is not allowed over DIFF
5505 0 BAD2HR HRES is not allowed over NPLUS
5506 0 BAD3HR HRES is not allowed over POLY1
5510 0 E1HRP2 Minimum HRES enclosure of POLY2 = 3
5512 0 S1HRP1 Minimum HRES to POLY1 spacing = 0.35
5514 0 S1HRP2 Minimum HRES to POLY2 spacing = 3
5516 0 S1DFHR  Minimum HRES to DIFF spacing = 0.35
5518 0 W1LV Minimum LVTDEF width = 0.6
5521 0 S1LVLV Minimum LVTDEF spacing = 0.6
5528 0 E1LVAA Minimum LVTDEF enclosure of DIFF = 0.25
5530 0 S1AALV Minimum LVTDEF to DIFF spacing = 0.35
5531 0 LVR001 LVTDEF over ZENER is not allowed
5533 0 LVR002 LVTDEF outside GATE is not allowed
5534 0 LVR003: LVTA outside SFCDEF will be removed and regenerated
5535 0 LFR001: LVPTUB outside SFCDEF will be removed and regenerated
5541 0 NMOSML_R1 Minimum GATE length of NMOSML = 0.5
5547 0 PMOSML_R1 Minimum GATE length of PMOSML = 0.5
5550 0 W1MC Minimum METCAP width = 4
5553 0 W2MC Minimum dummy METCAP width = 0.5
5563 0 W3MC Maximum METCAP size = 30
5564 0 W1M2  Maximum MET2 width (capacitor bottom plate ) = 35
5567 0 S1MCMC Minimum METCAP spacing = 0.8
5569 0 S1M2M2 Minimum MET2 spacing (capacitor bottom plate) = 0.8
5573 0 S1MCV1 Minimum spacing between VIA1 and METCAP = 0.5
5577 0 S1MCV2 Minimum spacing between VIA2 and METCAP = 0.5
5582 0 S1V2V2  Minimum VIA2 spacing on MET2 bottom plate outside METCAP = 4
5586 0 S2V2V2  Minimum VIA2 spacing on METCAP = 3.5
5591 0 E1M2MC Minimum MET2 enclosure of METCAP = 1
5602 0 E1M2V1 Minimum MET2 enclosure of VIA1 (capacitor bottom plate) = 0.2
5605 0 E1M2V2 Minimum MET2 enclosure of VIA2 (capacitor bottom plate) = 0.2
5609 0 E1MCV2 Minimum METCAP enclosure of VIA2 = 0.5
5611 0 R1MC Minimum METCAP density [%] = 3
5614 0 R1V2 Minimum VIA2 density inside METCAP [%] = 1
5615 0 BAD1M1 MET1 under METCAP region is not allowed
5630 0 CMIM_G1: cmim device over active or passive device not allowed
5631 0 CPOLY_G1 PPLUS on CPOLY is not allowed
5632 0 CPOLY_G2 NPLUS on CPOLY is not allowed
5633 0 RPOLY1_R1 PPLUS on RPOLY1 is not allowed
5634 0 RPOLY1_R2 NPLUS on RPOLY1 is not allowed
5635 0 RPOLY2_R1 PPLUS on RPOLY2 is not allowed
5636 0 RPOLY2_R2 NPLUS on RPOLY2 is not allowed
5637 0 RPOLY2P_R1 PPLUS on RPOLY2P is not allowed
5638 0 RPOLY2P_R2 NPLUS on RPOLY2P is not allowed
5639 0 RPOLY2PH_R1 PPLUS on RPOLY2PH is not allowed
5640 0 RPOLY2PH_R2 NPLUS on RPOLY2PH is not allowed
5643 0 E1IPCT Minimum PPLUS enclosure of POLY2CON = 0.6
5644 0 E1IPCT Minimum PPLUS enclosure of POLY2CON = 0.6 missing pplus
5653 0 S1IPP2 Minimum PPLUS to RPOLYH spacing = 0.35
5655 0 RPOLYH_G2 Minimum high precision RPOLYH width = 2
5657 0 W4P2 Minimum RPOLYZ width = 0.8
5660 0 S4P2P2 Minimum RPOLYZ spacing = 0.75
5662 0 S4P2P2 Minimum RPOLYZ spacing = 0.75 notch
5665 0 E2IPCT Minimum PPLUS enclosure of POLY2CON = 0.6
5666 0 E2IPCT Minimum PPLUS enclosure of POLY2CON = 0.6 missing pplus
5675 0 S2IPP2 Minimum PPLUS to RPOLYZ spacing = 0.35
5677 0 RPOLYZ_G2 Minimum high precision RPOLYZ width = 2
5681 0 AMTW1 AMTL1 fixed with of dummy MTOP thin blocks 2.0 x 5.0 U
5683 0 AMTS2  Minimum MTOP feature to dummy MTOP block spacing = 2
6371 0 AMTS1 Maximum MTOP spacing when the width of one or both MTOP shapes is less than 10um = 10
6476 0 AMTS3 maximum met4 to met4 block spacing
6479 0  AMTS4 fixed met4 block spacing (checked min only 2.0 U)
6481 0 NWR001 NTUB overlapping KEPOUT is not allowed
6483 0 S1KONW Minimum NTUB spacing to KEPOUT or SFCDEF = 3
6484 0 AAR001 DIFF overlapping KEPOUT is not allowed
6486 0 S1AAKO Minimum DIFF spacing to KEPOUT or SFCDEF = 0.6
6487 0 XMR002 MIDOX overlapping KEPOUT is not allowed
6489 0 S1KOXM Minimum MIDOX spacing to KEPOUT or SFCDEF = 0.6
6490 0 P1R002 POLY1 overlapping KEPOUT is not allowed
6492 0 S1KOP1 Minimum POLY1 spacing to KEPOUT or SFCDEF = 0.45
6493 0 NSR001 NPLUS overlapping KEPOUT is not allowed
6495 0 S1KONS Minimum NPLUS spacing to KEPOUT or SFCDEF = 0.6
6496 0 PSR001 PPLUS overlapping KEPOUT is not allowed
6498 0 S1KOPS Minimum PPLUS spacing to KEPOUT or SFCDEF = 0.6
6499 0 HRR004 HRES overlapping KEPOUT is not allowed
6501 0 S1HRKO Minimum HRES spacing to KEPOUT or SFCDEF = 0.6
6502 0 P2R002 POLY2 overlapping KEPOUT is not allowed
6504 0 S1KOP2 Minimum POLY2 spacing to KEPOUT or SFCDEF = 0.6
6505 0 COR002 CONT overlapping KEPOUT is not allowed
6507 0 S1COKO Minimum CONT spacing to KEPOUT or SFCDEF = 0.4
6508 0 M1R002 MET1 overlapping KEPOUT is not allowed
6510 0 S1KOM1 Minimum MET1 spacing to KEPOUT or SFCDEF = 0.45
6511 0 V1R002 VIA1 overlapping KEPOUT is not allowed
6513 0 S1KOV1 Minimum VIA1 spacing to KEPOUT or SFCDEF = 0.45
6514 0 M2R002 MET2 overlapping KEPOUT is not allowed
6516 0 S1KOM2 0.5
6517 0 V2R002 VIA2 overlapping KEPOUT is not allowed
6519 0 S1KOV2 Minimum VIA2 spacing to KEPOUT or SFCDEF = 0.45
6520 0 M3R002 MET3 overlapping KEPOUT is not allowed
6522 0 S1KOM3 Minimum MET3 spacing to KEPOUT or SFCDEF = 0.6
6523 0 PAR002 PAD overlapping KEPOUT is not allowed
6525 0 S1KOPA Minimum PAD spacing to KEPOUT or SFCDEF (not shown) = 9
6526 0 LVR004 LVTDEF overlapping KEPOUT is not allowed
6528 0 S1KOLV Minimum LVTDEF spacing to KEPOUT or SFCDEF = 0.6
6529 0 MCR002 METCAP overlapping KEPOUT is not allowed
6531 0 S1MCKO Minimum METCAP spacing to KEPOUT or SFCDEF = 0.8
6532 0 V3R002 VIA3 overlapping KEPOUT is not allowed
6534 0 S1KOV3 Minimum VIA3 spacing to KEPOUT or SFCDEF = 0.45
6535 0 M4R002 MET4 overlapping KEPOUT is not allowed
6537 0 S1KOM4 Minimum MET4 spacing to KEPOUT or SFCDEF = 0.6
6540 0 Recommendation: Fixed RESTRM enclosure of RESDEF edge 0.1
6543 0 Recommendation: Fixed RESTRM enclosure of TUBDEF edge 0.1
6548 0 Warning: Illegal Layout Convention: RESDEF/TUBDEF missing RESTRM
6551 0 Warning: Illegal Layout Convention: RESTRM missing RESDEF
6554 0 PWR001: FIMP outside SFCDEF will be removed and regenerated
6556 0 LDR001: NLDD outside SFCDEF will be removed and regenerated
6558 0  L2R001: NLDD50 outside SFCDEF will be removed and regenerated
6559 0 PYR001 PCOAT outside SFCDEF will be removed and regenerated
6561 0 Minimum PCOAT width = 15
6564 0 Minimum PCOAT spacing = 15
6565 0 REC002 PCOAT not multiple 45 degrees PCOAT
6568 0 W1BK Minimum PCOAT_black width = 2
6571 0 S1BKBK Minimum PCOAT_black spacing = 2.0
6573 0 S1BKPA Minimum PCOAT_blackto PAD spacing = 3.0
6576 0 S1BKSB Minimum PCOAT_black to CHIPEDGE spacing = 20.0
6579 0 W1CR Minimum PCOAT_clear width = 2
6582 0 S1CRCR Minimum PCOAT_clear spacing = 2.0
6584 0 S1CRPA Minimum PCOAT_clear to PAD spacing = 3.0
6587 0 S1CRSB Minimum PCOAT_clear to CHIPEDGE spacing = 20.0
6590 0 W1GN Minimum PCOAT_green width = 2
6593 0 S1GNGN Minimum PCOAT_green spacing = 2.0
6595 0 S1GNPA Minimum PCOAT_greento PAD spacing = 3.0
6598 0 S1GNSB Minimum PCOAT_green to CHIPEDGE spacing = 20.0
6601 0 W1RD Minimum PCOAT_red width = 2
6604 0 S1RDRD Minimum PCOAT_red spacing = 2.0
6606 0 S1PARD Minimum PCOAT_red to PAD spacing = 3.0
6609 0 S1RDSB Minimum PCOAT_red to CHIPEDGE spacing = 20.0
6612 0 W1BU Minimum PCOAT_blue width = 2
6615 0 S1BUBU Minimum PCOAT_blue spacing = 2.0
6617 0 S1BUPA Minimum PCOAT_blue to PAD spacing = 3.0
6620 0 S1BUSB Minimum PCOAT_blue to CHIPEDGE spacing = 20.0
6624 0 AR1_error_gate: AR1: Maximum ratio of floating POLY1 edge area to connected GATE area = 200
6626 0 AR2_error_gate: AR2: Maximum ratio of floating MET1 edge area to connected GATE area = 400
6628 0 AR3_error_gate: AR3: Maximum ratio of floating MET2 edge area to connected GATE area = 400
6630 0 AR4_error_gate: AR4: Maximum ratio of floating MET3 edge area to connected GATE area = 400
6632 0 AR5_error_gate: AR5: Maximum ratio of floating MET4 edge area to connected GATE area = 400
6633 0 rpoly1_g1_pres1_wexp: RPOLY1_G1: Minimum number of RPOLY1 squares = 5
6634 0 rpoly2_g1_pres_wexp: RPOLY2_G1: Minimum number of RPOLY2 squares = 5
6635 0 rpoly2p_g1_presp_wexp: RPOLY2P_G1: Minimum number of RPOLY2P squares = 5
6636 0 rpoly2ph_g1_presph_wexp: RPOLY2PH_G1: Minimum number of RPOLY2PH squares = 5
6637 0 rnwell_g1_nwres_wexp: RNWELL_G1: Minimum number of RNWELL squares = 5
6638 0 rpolyh_g1_presh_wexp: RPOLYH_G1: Minimum number of RPOLYH squares = 5
6639 0 rpolyh_g1_presz_wexp: RPOLYZ_G1: Minimum number of RPOLYZ squares = 3.75
6640 0 G01P1_net_poly1con: G01P1 Maximum ratio of POLY2 area to connected CONT area = 18000
6641 0 G01P2_net_poly2con: G01P2 Maximum ratio of POLY2 area to connected CONT area = 22000
6649 0 CBR1 PAD met2 not connected to met1
6650 0 CBR1 PAD met3 not connected to met2
6651 0 CBR1 PAD met4 not connected to met3
